"""Shared constants and helper functions used across the application."""

CASE_MODEL_ID = "casemodel.id"

RETURN_VALUE = 0


def normalize_route(route: str) -> str:
    """Strip trailing slash from a route path."""
    return route.rstrip("/")

RELATIVE_VIEWPORT_85 = "85vh"
RELATIVE_VIEWPORT_95 = "95vh"

ICON_TEST_TUBES = "test-tubes"
ICON_USERS = "users"

FIELD_ID = "id"

#region STATUSES
STATUS_EXECUTION_TO_DO = "To Do"
STATUS_EXECUTION_IN_PROGRESS = "in progress"
STATUS_EXECUTION_ON_HOLD = "on hold"
STATUS_EXECUTION_COMPLETED_FAILED = "[F] completed"
STATUS_EXECUTION_NOT_STARTED = "not started"
STATUS_EXECUTION_CLOSED = "closed"
STATUS_EXECUTION_COMPLETED = "completed"

STATUS_CYCLE_PASSED = "passed"
STATUS_CYCLE_FAILED = "failed"
STATUS_CYCLE_TESTING = "testing"
#endregion

#region CYCLE CHILD TYPE IDs
CHILD_TYPE_SUITE = 0
CHILD_TYPE_SCENARIO = 1
CHILD_TYPE_CASE = 2
CHILD_TYPE_STEP = 3
#endregion

#region SUITE CHILD TYPE IDs
SUITE_CHILD_TYPE_SCENARIO = 0
SUITE_CHILD_TYPE_CASE = 1
#endregion

#region ITERATION STATUS IDs
ITERATION_STATUS_NOT_STARTED = 0
ITERATION_STATUS_IN_PROGRESS = 1
ITERATION_STATUS_ON_HOLD = 2
ITERATION_STATUS_CLOSED = 3
ITERATION_STATUS_COMPLETED = 4
#endregion

#region SNAPSHOT STATUS IDs
SNAPSHOT_STATUS_TO_DO = 0
SNAPSHOT_STATUS_FAILED = 1
SNAPSHOT_STATUS_PASS = 2
SNAPSHOT_STATUS_SKIPPED = 3
SNAPSHOT_STATUS_BLOCKED = 4
#endregion

#region MESSAGES
MESSAGE_ALREADY_IN_LIST = "already in list"
MESSAGE_PREREQUISITE_ALREADY_IN_LIST = "prerequisite " + MESSAGE_ALREADY_IN_LIST
#endregion