CASE_MODEL_ID = "casemodel.id"

RELATIVE_VIEWPORT_85 = "85vh"
RELATIVE_VIEWPORT_95 = "95vh"

ICON_TEST_TUBES = "test-tubes"
ICON_USERS = "users"

FIELD_ID = "id"

#region STATUSES
STATUS_EXECUTION_TO_DO = "To Do"
STATUS_EXECUTION_IN_PROGRESS = "in progress"
STATUS_EXECUTION_ON_HOLD = "on hold"
STATUS_EXECUTION_COMPLETED_FAILED = "[F] completed"
STATUS_EXECUTION_NOT_STARTED = "not started"
STATUS_EXECUTION_CLOSED = "closed"
STATUS_EXECUTION_COMPLETED = "completed"

STATUS_CYCLE_PASSED = "passed"
STATUS_CYCLE_FAILED = "failed"
STATUS_CYCLE_TESTING = "testing"
#endregion

#region MESSAGES
MESSAGE_ALREADY_IN_LIST = "already in list"
MESSAGE_PREREQUISITE_ALREADY_IN_LIST = "prerequisite " + MESSAGE_ALREADY_IN_LIST
#endregion